#!/bin/bash		### Honu's .bashrc

PRINTER=lp
VISUAL="emacs -nw"
EDITOR="emacs -nw"
BROWSER=google-chrome:firefox:iceweasel
export VISUAL EDITOR BROWSER

appendToPath () {
    if [ -d $1 ]; then
	(echo "$PATH" | grep -q $1)  || PATH=$PATH:$1
    fi
}
prependToPath () {
    if [ -d $1 ]; then
	(echo "$PATH" | grep -q $1)  || PATH=$1:$PATH
    fi
}

appendToPath /opt/bin
prependToPath $HOME/bin
for d in `ls -d $HOME/Honu/local/{bin,[a-z]*_bin} 2>/dev/null`; do prependToPath $d; done
for d in /opt/java/bin /usr/local/java/bin; do prependToPath $d; done

export PATH

if [ "$PS1" ]; then
  # We're in an interactive shell.  Start by changing the prompt:

  PS1='(\h $USER\W \!) '

  case "$TERM" in
      xterm*)
	  PS1='\[\033]1;\h:\u\]\[\033]2;$USER@\h \w\](\h \W \!) ';;
  esac
  
  export ignoreeof=0

  if [ ! -z $WS ]; then
      # If we know what workspace this terminal is on, give it its own history file
      HISTFILE=$HOME/.bash_history_$WS
  fi

  # At some point I will move the aliases and functions to .aliases,
  # which would let them be used by zsh

  getmail () {
      fetchmail | grep -v skipping | grep -v 'No mail' \
	  >> /home/steve/logs/fetchmail.log
  }

  # cd. cd's to the *real* current directory to make .. work properly
  cd.() {
      if [ -z "$1" ]; then cd -P .; else cd -P "$1"; fi
  }

  # . f - functions as source (the usual definition) if f is an ordinary file,
  #       if f is a directory, cd -P to it and print useful info.
  .() {
     if [ "$1" = "" ]; then 
	cd.; dirs; ls -aCF --color=auto
     elif [ -d $1 ]; then
	cd. $1; dirs; ls -aCF --color=auto
     else
	source $1
     fi
  }

  # , f -> cd. ../$1   Note that ".." is now just a cd (because of shopt -s autocd)
  ,() {
      cd. ../$1; dirs; ls -aCF --color=auto
  }

  # rather than redefining .. we simply set autocd, which makes every directory name
  # a cd command.
  shopt -s autocd

  alias a="audacity --sync"
  alias h=history
  alias j=jobs
  alias p=pushd
  alias P=popd
  alias gf=grep-find
  alias ll='ls -alF --color=auto'
  alias lr='ls -aRF --color=auto'
  alias l='ls -aCF --color=auto'
  alias lp2s='lp -o sides=two-sided-long-edge'
  alias chrome="google-chrome >& /dev/null"
  alias gnus="emacs -f gnus -name gnus"
  alias pidgin="pidgin -f"
  alias bed="ssh root@localhost acpitool -s"
  alias todo="emacs -geometry 91x35 to.do&"
  
  # Chain in local/[a-z]*_aliases, which might have been put there by Myrtle et. al.
  for f in `ls $HOME/Honu/local/[a-z]*_aliases 2>/dev/null`; do source $f; done
  
  # enable bash completion in interactive shells
  if [ -f /etc/bash_completion -a -z "$BASH_COMPLETION" ]; then
      . /etc/bash_completion
  fi

  # make an alias for frm in case it's missing.  No use in scripts, of course.
  [ -x /usr/bin/frm ] || [ -x /usr/local/bin/frm ] \
      || alias frm='echo x | mail| tail +2'
fi

# Chain in local/[a-z]*_bashrc, which might have been put there by Myrtle et. al.
for f in `ls $HOME/Honu/local/[a-z]*_bashrc 2>/dev/null`; do source $f; done

# Console xterm on my ctwm dashboard.
[ x"$CONSOLE" != x ] && { unset CONSOLE ; $HOME/bin/idle& }
