#!/bin/bash		### Honu's .bashrc

PRINTER=lp
VISUAL="emacs -nw"
EDITOR="emacs -nw"
BROWSER=google-chrome:firefox:iceweasel
export VISUAL EDITOR BROWSER

(echo "$PATH" | grep -q "$HOME/bin")  || \
    PATH=$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:$PATH:/opt/bin

appendToPath () {
    if [ -d $1 ]; then
	(echo "$PATH" | grep -q $1)  || PATH=$PATH:$1
    fi
}
prependToPath () {
    if [ -d $1 ]; then
	(echo "$PATH" | grep -q $1)  || PATH=$1:$PATH
    fi
}

appendToPath /opt/bin
prependToPath $HOME/bin
prependToPath $HOME/Honu/local/local-bin

if [ -d /opt/java/bin ]; then
    PATH=/opt/java/bin:$PATH
elif [ -d /usr/local/java/bin ]; then
    PATH=/usr/local/java/bin:$PATH
fi

export PATH

if [ "$PS1" ]; then
  # We're in an interactive shell.  Start by changing the prompt:

  PS1='(\h:$USER\W \!) '

  case "$TERM" in
      xterm*)
	  PS1='\[\033]1;\h:\u\]\[\033]2;\h:$USER \w\](\h:\W \!) ';;
  esac
  
  export ignoreeof=0

  # At some point I will move the aliases and functions to .aliases,
  # which would let them be used by zsh

  getmail () {
      fetchmail | grep -v skipping | grep -v 'No mail' \
	  >> /home/steve/logs/fetchmail.log
  }

  # cd. cd's to the *real* current directory to make .. work properly
  cd.() {
      if [ "$1" != "" ]; then cd "$1"; fi
      cd `/bin/pwd`
  }

  .() {
     if [ "$1" = "" ]; then 
	cd.; dirs; l
     elif [ -d $1 ]; then
	cd. $1; dirs; l
     elif [ -d ../$1 ]; then
	cd. ../$1; dirs; l
     elif [ -f $1 ]; then
	source $1
     fi
  }

  alias a="audacity --sync"
  alias p=pushd
  alias P=popd
  alias ll='ls -alF --color=auto'
  alias lr='ls -aRF --color=auto'
  alias l='ls -aCF --color=auto'
#  alias chrome="google-chrome --allow-outdated-plugins >& /dev/null"
  alias chrome="google-chrome >& /dev/null"
  alias gnus="emacs -f gnus -name gnus"
  alias pidgin="pidgin -f"
  alias bed="ssh root@localhost acpitool -s"
  alias todo="emacs -geometry 91x35 to.do&"

  # enable bash completion in interactive shells
  if [ -f /etc/bash_completion -a -z "$BASH_COMPLETION" ]; then
      . /etc/bash_completion
  fi

  # make an alias for frm in case it's missing.  No use in scripts, of course.
  [ -x /usr/bin/frm ] || [ -x /usr/local/bin/frm ] \
      || alias frm='echo x | mail| tail +2'
fi

# Chain in a local_bashrc, which might have been put there by Myrtle
[ -f $HOME/Honu/local/local_bashrc ] && source $HOME/Honu/local/local_bashrc

# Console xterm on my ctwm dashboard.
[ x"$CONSOLE" != x ] && { unset CONSOLE ; $HOME/bin/idle& }
