#!/bin/csh -f
#  cptree src dst
#  	$Id: cpltree,v 1.1 1997-09-19 04:27:18 steve Exp $
#
# 	copy a directory tree (on the same machine)
# 	STAY ON ONE FILE SYSTEM

if ($#argv != 2) then
	echo usage: $0 src dst
	exit
endif
if (! -e $2) mkdir $2
(cd $1; tar clf - .) | (cd $2; tar xvpBf -)
