#!/bin/csh -f
#  cptree src dst
#  	$Id: cptree,v 1.1 1997-09-19 04:27:18 steve Exp $
# 	copy a directory tree (on the same machine)
#
if ($#argv != 2) then
	echo usage: $0 src dst
	exit
endif
if (! -e $2) mkdir $2
(cd $1; tar cf - .) | (cd $2; tar xvpBf -)
