#!/bin/sh
#	$Id: crcssh,v 1.2 2011-05-20 15:16:43 steve Exp $ 
#	crcssh host command...
#	export CVS_RSH=crcrsh ; cvs update
# Note that the host is a dummy: we always end up on leaf.
[ -z $1 ] || shift
#ssh -p 40000 205.226.66.127 $*
ssh tol.rii.ricoh.com $*
