#!/bin/bash
#  $Id: daily,v 1.3 2011-05-20 15:16:43 steve Exp $
#  Called from ./idle in the X console window, and sometimes crontab.

# === really should split idle and crontab versions ===

cd

### Email reminders, if there are any

if [ -x /usr/bin/ical ]; then
   # could probably just use the command here...
   bash -c 'source .profile; /usr/bin/ical -list > remind'
   # was using -calendar /pia1/home/steve/.calendar -list
   if [ -s remind ]; then
      mail -s "REMINDERS: `date`" steve@theStarport.org < remind
   fi
fi

### See whether we can run backups over ssh

sshOK=false
[ -z $SSH_AUTH_SOCK ] || sshOK=true

function backups() {
    # Do the backups if there's a mirror mountpoint on this machine
    # It's done in idle because we need ssh for nova's root partition
    #
    if [ -d /mirror ] && [ -x /usr/local/sbin/daily-mirror ] && $sshOK; then
	ssh -x root@localhost /usr/local/sbin/daily-mirror -v < /dev/null
    fi	
}

# Email a status ping:  uptime, disk, users, and backup report
(uptime; df; backups; w) \
    | mail -s "STATUS: `hostname` `date +%Y-%m-%d`" \
      steve@theStarport.org steve@rii.ricoh.com


