#!/bin/csh -f
#	$Id: du-x,v 1.1 1997-09-19 04:29:26 steve Exp $
#	Run xdu < .du with an appropriate label.
#
# df . produces something like:
# wd 1: filesystem kbytes used avail capacity Mounted on
# wd 8: towerhost:/sci/local 943278 620858 228092 73% /tmp_mnt/usr/local

if ($#argv == 0) set argv = .
@ xy = 0

foreach f ($argv)
  cd $f
  set df = `df . | tail -1`
  if ("$f" == ".") then
     set dir = $cwd:t
  else
     set dir = $f
  endif
  xdu -name "xdu: $dir $df" -g 600x800+$xy-$xy < .du &
  @ xy = $xy + 10
end
