#!/bin/csh
#	xr5 [command...]
#	execute the command in an R5 environment.
#
#	can also be sourced in .cshrc -- some of the environment
#	variables, e.g. XREV, are intended to simplify this, e.g. 
#	you can put the following in your .cshrc:
#	  if (-e /usr/local/bin/xr5 && ! "$?XREV") source /usr/local/bin/xr5

setenv XREV  R5
setenv XHOME /usr/local/X11R5
setenv XSRC  /rhine1/src/X11R5
setenv XBIN  $XHOME/bin
setenv XLIB  $XHOME/lib
setenv XINC  $XHOME/include

if (! $?MANPATH) setenv MANPATH /usr/local/man:/usr/man
setenv MANPATH $XHOME/man:$MANPATH

if (! $?LD_LIBRARY_PATH) setenv LD_LIBRARY_PATH /usr/lib
setenv LD_LIBRARY_PATH ${XLIB}:/LD_LIBRARY_PATH

set path = ( $XBIN $path )

$*
