#!/bin/sh
#
# Set up X applications on, e.g., nova.  Assumes a single 1920x1200 monitor,
# which has room for two conky's, an xterm, and xdaliclock along the right-
# hand edge.
# Run with:  ssh -X nova xsetup

xdaliclock -noseconds -geometry 408x163-0-424&
conky -a br&
exec xterm -fg green -geometry  72x13-0+411
