#!/bin/sh
# bottom-mobars [-k | N...]
#    Display a bottom bar on each of the listed screens, or kill them all.

if [ "$1" = "-k" ]; then
    # If we don't exec, it will complain because it tries to kill its parent.
    exec killall bottom-mobars
fi

HOST=`hostname`

monitor () {
    case $1 in
	(1) echo '1(w)';;
	(2) echo '2(e)';;
	(3) echo '3(r)';;
	(*) echo $1 ;;
    esac
}

up () {
    echo u$( uptime | cut -d u -f 2- \
	   | sed -e 's/ min/m/' -e 's/ users/u/' -e 's/ days*,/d/' -e 's/load average/ld/'
	   ) 
}

status () {
    echo   $HOST '<fc=#eeeeee>'`monitor $1`'</fc>,' `up`
}

for s in $*; do 
    while :; do status $s; sleep 10; done | xmobar -x $((s - 1)) ~/.xmonad/xmobarrc-status &
done 

