#!/bin/sh
# apt-get packages for multimedia.

# These are what you want for audio editing.
sudo apt-get -y install audacity ams \
      tap-plugins swh-plugins ladspa-sdk mcp-plugins fil-plugins rev-plugins	\
      vco-plugins libfftw3-3 libfftw3-dev amb-plugins ams cmt lam-mpidoc	\
      sfftw-dev

# CD and DVD ripping
sudo apt-get -y install jack dvdrip-doc dvdrip xine-ui subtitleripper		\
     abcde icedax id3 id3v2 eyed3 vorbisgain mkcue glyrc
 
