#!/bin/sh
# apt-get packages for xmonad and friends on Debian or Ubuntu

sudo apt-get -y install xmonad libghc-xmonad-dev trayer        \
     dzen2 suckless-tools                                      \
     xfce4-terminal xfce4-power-manager xdotool wmctrl         \
     classicmenu-indicator ansiweather lm-sensors	       \
     x11-xserver-utils xterm gsimplecal fbpanel sysbench

if grep -qs "trusty main" /etc/apt/sources.list; then
    echo "we appear to be on Ubuntu 14.04 -- skip xmobar"
else
    sudo apt-get -y install xmobar
fi
