#!/bin/sh
# bottom-bars [-k | N...]
#    Display a bottom bar on each of the listed screens, or kill them all.

FONT="xft:Bitstream Vera Sans:size=12:antialias=true"
DZEN_OPTS="-bg black -fg #646464 -ta r "

if [ "$1" = "-k" ]; then
    kill `ps x | grep [b]ottom | cut -d p -f 1`
    exit 0
fi

monitor () {
    case $1 in
	(1) echo '1 (w)';;
	(2) echo '2 (e)';;
	(3) echo '3 (r)';;
	(*) echo $1 ;;
    esac
}

up () {
     echo u`uptime | cut -d u -f 2- | sed -e 's/ days,/d/' -e 's/load average/ldavg/'` 
}

weather () {
    echo 'SEA Temp:'`ansiweather -a false -l Seattle,WA -u imperial | cut -d '>' -f 2- | \
         sed -e s/idity// -e s/sure// -e 's/ =>/:/g'`
}

status () {
    echo 'screen' `monitor $1` on `hostname` '||' `up` '||' `weather` \
	 '||^fg(white)' `date '+%a %b %d %I:%M%P'` ' '
}

for s in $*; do 
    while :; do status $s; sleep 60; done | dzen2 $DZEN_OPTS -fn '$FONT' -geometry -0-0 -xs $s &
done 

