#!/bin/sh
# bottom-bars [-k | N...]
#    Display a bottom bar on each of the listed screens, or kill them all.

FONT="xft:Bitstream Vera Sans:size=12:antialias=true"
DZEN_OPTS="-bg black -fg #646464 -ta r "

if [ "$1" = "-k" ]; then
    kill `ps x | grep [b]ottom | cut -d p -f 1`
    exit 0
fi

text () {
    echo 'SEA Temp ='`ansiweather -a false -l Seattle,WA -u imperial | cut -d '=' -f 2-` \
	 '||' u`uptime | cut -d u -f 2-` '||^fg(white)' `date '+%a %b %d %I:%M%P'` ' '
}

for s in $*; do 
    while :; do text; sleep 10; done | dzen2 $DZEN_OPTS -fn '$FONT' -geometry -0-0 -xs $s &
done 

