#!/bin/sh
#    Sourced by the xmonad gdm/lightdm session.  Initially from
#    /usr/share/doc/xmonad/README.Debian

xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 -solid blue

#xrdb -merge .Xresources

trayer --edge top --align right --SetDockType true\
       --SetPartialStrut true --expand true\
       --widthtype percent --width 10 --height 20\
       --transparent true --tint 0x000000 &

gnome-settings-daemon&

# equivalent to eval -- sources the output to set variables.
$(gnome-keyring-daemon --start --daemonize)

if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 1
   gnome-power-manager &
fi

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

export LC_COLLATE=C

# xscreensaver on gnome-oriented distros is old and crufty.
gnome-screensaver&

#if [ -e $HOME/.xmonad/.Xmodmap ]; then xmodmap $HOME/.xmonad/.Xmodmap; fi
#Apparently any use of xmodmap on Ubuntu turns off VT switching!


